# Generated by Django 3.2.8 on 2021-10-17 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='User',
            new_name='user',
        ),
    ]
